version: "3.8"
services:
  php:
    build: .
    container_name: ifgaccess-apache
    volumes:
      - ./src/:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: ifgaccess-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
    # Descomente para acessar o banco diretamente do host (somente em desenvolvimento)
    ports:
      - "3306:3306"

volumes:
  mysql_data:
